-- Seed suppliers from Vendor List (977 entries)
-- Run in Neon SQL Editor
-- Supplier schema: id, name, phone, category, status, createdAt, updatedAt

INSERT INTO "Supplier" (id, name, phone, category, status, "createdAt", "updatedAt")
VALUES
  (gen_random_uuid(), 'BUILDING ART', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CK BETON CEMENT INDUSTRIES LLC', '02 5512213', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARAB BUILDING MATERIALS LLC', '02 5554052', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALI AL QUTIBI HARDWARE TRADING LLC', '02 5538786', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SULTAN PRECAST CONCRETE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CITY WAY SANITARY WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LEBANESE MAGIC GENERAL MAINTENANCE EST', '055 2320276', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL FURAT BEACH AC CONTRACTING', '050 8585759', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHIRAZ INSULATION MATERIALS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PHOENIX GULF GENERAL CONTRACTING', '02 5521950', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMAD FAROOQ', '050 5320422', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SAMRA ELECTRICAL CO LLC', '02 5509575', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MAYADEEN STARS GEN. MAINTENANCE LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALED NOURY AL ALI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ISLAMABAD GEN. TRANSPORT', '02 5525336', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TAXI PICK UP SERVICES', '050 4140134', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARAB TOWER INTL. TRADING CO. LLC', '02 5544334', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'JORDAN NATURAL STONE MARBLE CENTER LLC', '02 5554469', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL WATHBA SERVICES', '02 5075000', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL RAMZ AL THANI TOWING CARS & GENERAL', '050 5828867', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ISTAQAMA GENERAL TRANSPORT EST', '025510915', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL KOUTHAR MECHANICAL EQUIPMENT', '02 5554654', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KING ROADS TRANSPORT & VEH. REC', '050 1314542', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMAD YAQOOB', '02 5597675', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SPECTRUM GLASS LLC', '02 5597675', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'POWER PACK ELECTRICAL & PLUMBING', '02 5537895', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GULF BRIDGE GENERAL TRANSPORT & RECOVER', '050 7011639', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PERFECT BUILDING COMMERCIALS BROKERS', '02 5538338', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AHMED FOAD SAEED', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MASHRIR FLOWER REIN. CARPENTRY & PLA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Parker Russel Accounting', '02 6452666', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MODERN ACHEIVEMENTS PAINTING & PLASTERI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'JAMAL HAMAD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UNITED ELECTRONICS', '02 6777701', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HAMEED SAEED AL HASANY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'JAHANGIR ALAM BLACKSMITH & WELDING', '02 5548707', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CICON BUILDING MATERIALS', '02 5500050', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAFIQ ULLAH KHAN MOHAMMAD SHER ALI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'JIDAR CONSULTANT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MANAA METAL CONSTRUCTION CO.', '02 5513012', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GHANOON GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EMIRATES CHINA COMMERCIAL CENTER', '02 5555011', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MIQYAS CARPENTRY & DECOR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ORIENT ELECT. CONT', '02 5507655', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SYED JAWAD  SHAH', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BASAM FARIS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABDUL QADER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'STAR LIGHT BUILDER MATERIALS', '02 5544184', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'WARIS ALIBUS SERVICES', '02 4439005', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SHABKA AL MASEYA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KABANI & COMPANY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABDUL RAHMAN AL ZUBEDI', '02 6423567', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MERDASS TRADING EXT', '02 6732765', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BAYADER CORNER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GULF ISLANDS GENERAL TRADING EST', '02 6325250', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NABEEL ALZAABI REINFORCED CARPENTRY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HAYTAM KHODAIR WAKKAA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHOUKAT HAYAT MOHAMMAD ALI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NAWAZ MARJAN RASHOOL KHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MASHUQ ALI MOHAMMAD ASHIQ', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PALM JUMEIRAH', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CAPTION INTERNATIONAL DECOR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHABIR AHMED MUHAMMAD SHARIF', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABU HAMADA  PLASTERING & PAINTING WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAEED ABU  BAKER GEN CONT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL DANUBE BUILDING MATERIALS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL WATHBA NATIONAL INSRURANCE CO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DR. ASYSHA AL KHAZRAJI AUDITING OFFICE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ADVANCED WAY BUILDING MATERIAL TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AGA BUILDERS SQUARE MARBLE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARAB GEOTECH FOR SOIL INVESTIGATION LAB', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UTMOST BUILDING MATERIALS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UMER DARAZ MOHAMMAD SHARIF', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DOLPHIN INSULLATION MATERIALS FIXING', '025579940', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RASHED MUHAIRY GROUP', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HI-TECH CONCRETE PRODUCTS', '02-5509112', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AMAN ULLAH MOHAMMAD SHARIF', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PINE STYLE METAL INDUSTRIES EST.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAWAEED EMPLOYMENT LLC', '025594444', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAYSAN COMPANY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AHMED KHAN REHMAT TILES WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'POLYCON GULF LIMITED', '02-505-9160', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NOVA KITCHEN', '02-6444854', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARTECO CERAMICS LLC', '026413434', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ASWAR ALGANOUB OF GYPSUM WORKS', '0569458409', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ROSE CERAMICS & SANITARY WARES LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABU RASHID MARBLE & PLASTERING WORKS', '0503311980', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL JAZEERAH METAL KITCHENS', '5334089', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MUSAFER HUSSAIN DECOR WORK EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RASHEED ASHRAF MOHAMMAD ASHRAF', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'VALENCIA BLDG. MAT TR. LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MURABAA BANIYAS GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'INTERNATIONAL POOLS EST.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAHMAN GEN. TRANSPORT/AZIZ RAHMAN GUL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABDULLAH MUBARAK ALI AL GHAITHI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GIFT LINE BLACKSMITH W/ SHOP', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'URGENT GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LIGHT STONE FACTORY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DONGYU INTERNATIONAL TRADE FZCO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALNAKHEEL DOORS & WINDOWS FIXING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SARWASA GENERAL TRANSPORT', '0551148110', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'JHELUM INT''L GEN. TRANSPORT', '0502584986', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CHEEMA GENERAL MAINTENANCE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'c/o Mr. Hesham  - Supervisor Site', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ADNOC Distribution', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALAF MOHAMED AHMAD ELEC.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL REEM BUILDING MATERIALS', '052634163', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SKYPARK ABU DHABI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Emirates Tools Est.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ZAKER HOSSAIN TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABDUL REHMAN GHULAM W/SHOP', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAHMOUD AHMED BUILDING MATERIAL LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BADIYA GENERAL TRANSPORT LLC', '0503231578', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TECHNICAL METAL INDUSTRIAL CO. LLC', '025502025', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ORCHIDIA HOME DECORATION & GENERAL MIAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MOHANNAD TRAD. & IMP. CO', '03-722-0555', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FUJAIRAH ROCKWOOL FACTORY', '092222297', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SULMAN ABDULLAH FAZAL HUSSAIN', '0508283695', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MASHRIQAIN CONT & GEN MAINT', '024457883', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'STYRENE INSULATION INDUSTRY', '025511166', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TIMEX INFORMATION TECHNOLOGY CONSULTING', '026769612', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALAF MOHAMED BUILDING MATERIAL TRADIN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FADHL ALUMINIUM & GLASS TR. LLC', '065441582', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RED SEA HORSE TECHNICAL WORKS', '04-2549661', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'S.S. LOOTAH TRADING BUILDING MATERIALS', '04-2099322', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Qaisar Entertainment Equipment Tradi', '067466939', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LIFE TUNE CONTRACTING & GEN. MAIN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GOLDEN MODEL GEN. CONT. LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MADA GYPSUM SYSTEMS LLC', '0504567683', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ISSAM ABDEL AZIM MOHAMED MOHAMOUD ZAHER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL TAWOOS AL THAHABI COMMERCIAL BROKER', '0502177007', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BEST WAY INTERIOR DECORATION LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARABELA COMMERCIAL BROKERS', '025826617', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SABRA GENERAL STEEL & ALUMINIUM EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CHINA KING INDUSTRIAL GROUP CO. LTD', '0086-22-60767280', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FIRMAN GEN TRANSPORTING', '0501494007', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABDULAA AL MARZOUQI GEN TRANSPORT', '0506157621', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Muhairy -Rent Office', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Naeem Aslam Mohammed Aslam', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SUN RISE ORNAMENT TILES FACTORY', '042225900', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EASY WAY TECHNICAL EQUIPMENT TRADING', '025514982', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BRITAIN DECORATION EST', '025513900', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'WHITE PALACE EST FUR. & DECOR.', '024466822', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MASTERLINE BLOCK TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'IBLA AL SHAM METALIC STRUCTURE CO. LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SKY CORNER GENERAL MAINTENANCE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ROYAL FOR EMPLOYEMENT SERVICES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GOLDEN BEAM STEEL ALUMINUM WORKS', '0557519662', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SUPERWAY ELECTRICAL EQUIPMENT TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALWAFI KITCHEN AND CABINETS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SOTUHERN ALWAHA GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PLANT ME NURSERY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL DIYAR AUTOMOBILE AUCTION', '05078442', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'IMTIAZ AHMED MIAN PLASTER & TILES CONT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SMART SPACE INTERIOR DESIGN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'THE CITY CRYSTAL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KIWAN CONSTRUCTION & BUILDING CO LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ZOUHIR YOUNES AL MOUR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HOT TIME ELECTRICAL & MECHANICAL CONT', '0557466483', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NEON TOWER ELECTRICAL TRAIDING', '025538835', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MUTAREF CEMENT PRODUCTS & GYPSUM', '0508188930', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABDEL SALAM FUAD SALEH AHMAD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ONLINE ALUMINIUM & GLASS WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'U.A.E ENTERPRISES CO.', '025559338', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ZAD AL KHAIR BUILDING MATERIALS EST', '037220242', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL JASEM GEN TRANSPORT EST', '025552675', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TEAM ALFA REAL ESTATE LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ATTRACTIVE TOWER PROPERTY MGMT T LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RASHID SAIF RASHID', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FIRST MEDIA ADVERTISING PUBLISHING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL RAIE TENTS & METAL WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TAIF ALWAFY GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CAPITAL ENGINEERING CONSULTANCY LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAJESTIC HOME DECORATION LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAND ROAD FOUNDATION DRILLING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EISSA HELAL BUILDING MATERIALS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ADMIX HARDWARES TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FAST WAY GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DELTA GENERAL TRANSPORTING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALL KINDS OF HEAVY EQUIPMENT', '0553879089', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMED ABDELAAL HELAL ELDEIB', '0553234531', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'QALAT AL JABAL CARPENTRY & SMITHERY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'STYRO INSULATION MAT. IND LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BANOOSH TECHNICAL SERVICES LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'IVORY MOUND GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL WASEEL GEN TRANSPORT EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAMDOUH DEYAB ABOILA TAHER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GREEN SCOPE STEEL INDUSTRIES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EXTRA CO FIBRE GLASS & PREFAB HOUSES LL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MUHAMMAD RISWAN METAL SCRAP TR.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL NAHDA NATIONAL INSURANCE BROKER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL TELOU BUILDING MATERIALS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL FAJER TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EAGLE COUNTRY GEN TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'STRADA TECHNICAL WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL AIN CERAMIC AND DESIGN FACTORY DS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABDOLLAH GHOLAM MANDEGARI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL TAGREER TRANSPORT & GEN. CONT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EMIRATES ELECTRICAL & PLASTIC INDUSTRIE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMED TARIQ', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TILAL HUMOS GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMAD TAYEB ABDULJABBAR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SEVEN SEAS STEEL INDUSTRIES LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EMDAD INTERNATIONAL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAJID HUSSAIN SABIR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'QAYUM KHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL HAKAM LOGISTICS TRANSPORT, CONTRACTI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DIRECTION GEN. CONTRACTING EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HALA GROUP', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BURJ AL BANAFSAEG Building Materials', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SAQIA TRADING EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'JABAL ALNOOR FOUNDATIONS DRILLING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'VALENCIA MARBLE', '037220778', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL HADI CONTRACTING CO', '026735756', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SILVER ROSE GEN. MAINTENANCE LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BILDCO CEMENT PRODUCTS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GREEN SKY MARBLE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAGIC VIEW GENERAL MAINTENANCE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AZZA EHAB MORSY AHMED', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL RAMAHI International Trading FZE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ETISALAT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOASHER ALEBDAA ELECRTRICAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARABIAN PENINSULA FOR CONCRETE PRODUCTS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NASSAR IQBAL TAHIR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'IRFAN MAHMOOD MUHAMMAD YAQOOB', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AEISH GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FAST WAY LINE TRUCK TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NOOR MAT KHAN KHAISTA KHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHAKEEL AHMED', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FOUR STAR GENERAL TRANSPORT EST', '055-9196697', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KAMAL ABU ALUFA OSMAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SINAA STEEL COMMERCIAL BROKER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAQR AL AHRAM TECHNICAL WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'POWER LINES ELECTROMECHANICAL', '025868875', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMD KHALIFA RASHWAN OTHMAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TERMINEX PESTS CONTROL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FAISAL ARTS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABU DHABI GENERAL TRANSPORT COMPANY', '025555700', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL HADHOUD TRADING & CONT EST', '025548811', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHIFT TYPING & PHOTOCOPYING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AREEJ ATAR PAINTS WORKS & DECORATIONS', '0501405776', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ZAINAB HARDWARE TRADING ESTABLISHMENT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GEMINI BUILDING MATERIALS LLC', '025538884', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MEEQAT TRANSPORT LLC', '02-6760601', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMAD IJAZ NOOR KHAN', '0559902051', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABU DHABI DISTRIBUTION CO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'WHITE ALUMINIUM ENT LLC', '025500830', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SARHAD GENERAL MAINT', '0507706849', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'METRO MECHANICAL EQUIPMENT LLC', '025556717', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMAD ARIF GHAFOOR', '0523056043', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAK CERAMICS', '026797366', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KLUDI RAK', '050-646-0597', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CONCRETE CREATIVE CONCEPT', '065321119', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MAJED METAL INDUSTRY', '067431044', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UNION CARPENTRY', '0507315270', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOSTAWA ALRAFEA TECHNICAL WORKS', '050-522-9630', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ISTANBUL ELECT WARE TRDG', '02-551-2521', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAFETY ELECTRICAL TRADING COMPANY WWL', '02-555-9259', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DRINGKING WTAER', '055-371-3661', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'JABROOT STEEL SUPPLY COMPANY LLC', '02-554-5056', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NATIONAL REINFORCE & CARPENTRY', '056-211-1286', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MODERN MACHINERY TRADING CO LLC', '06-534-6699', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DHOOA SHUROOQ GENERAL TRANSPORT', '050-816-2492', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ZAHRAT AL MAQAM GEN TRANSPORTING', '050-580-0564', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NATIONAL PAINTS FACTORIES CO. LTD', '06-513-0003', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'JAMEEL RENTING A BUSES EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SODAMCO SAL ABU DHABI', '02-550-9994', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BAYT AL SHARQI ORNAMENTATION FACTORY', '03-7211922', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FARAIDOONI TRADING CENTRE', '02-642-6237', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TAQEEF TRADING EST', '02-672-7684', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAMA AL RAYAN ALUM & GLASS CONT', '055-375-8085', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DAYLIGHT COMMERCIAL PRINTING PRESS', '02-6425442', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AMR ABDO MOHAMED SAID BARAYA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HUIDA AND TIENS GROUP FZCO', '04-3687482', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAS ALNGEL PLASTER TILES AND CONCRETE', '0558230793', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMAD AWADH AL KATHIRI CONT & GEN MAI', '055-1631713', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TASAWAR HUSSAIN TECHNICAL SERVICES LLC', '050-7654079', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EBLA BUILDING MATERIALS LLC', '025548270', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HYDRO SANITARY WARE TRADING', '02-554-8562', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'COLMEF BUILDING MATERIALS SPECIALITIES', '02-5511949', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MAJID STATIONERY AND OFFICE EQUIPMEN', '02-6446966', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SALAMA ISLAMIC INSURANCE CO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'OVERSEAS CEMENT INDUSTRIES LLC', '02-5828503', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NOR SHANDI GENERAL CONTRACTOR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ROYAL WAY GENERAL TRANSPORT', '0502659295', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GOLDEN LINE HARDWARE SUPPLIES LLC', '02-676-6070', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAFETY PALACE CONSTRACTING & GENERAL MA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAS AL HIKMA FOR ELECT & PLUMB CO LLC', '050-9052946', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL HOSAM HARDWARE TRADING', '050-414-3486', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EMIRATES CERAMIC', '02-6715500', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BAIT ALSALAM IMPORTING & TBM', '02-5655509', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAGHAD ALWADI PLASTERING & BLOCK WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HADDAD SANITARY CONTRACTING EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CITY LINK TILES AND MARBLE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NOBEL EQUIPMENT RENTING', '02-555-6226', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CARNEIGIE CONTRACTING & GENERAL MAIN', '02-4412766', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TOOLS LINE HARDWARE LLC', '025522940', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ELEGANT INTERIORS', '0553887739', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EXPANSION & RETRACTION GEN TRANSPORT', '0506710543', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GUL ABBAS GULAP', '0507787435', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GHAZI MUHAMMAD SERDALI KHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL KHALID FURNITURE FACTORY LLC', '048802011', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LAHORE FALCON GENERAL TRANSPORT', '025544729', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RIZWAN AHMED MUHAMMAD SHAFI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NADEEM UL HASSAN MOHAMMAD', '0508365241', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALKHTOT ALARDIA TRANSPORT AND GEN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ELECTRONIC & ENG. INDUSTRIES CO', '06-5332114', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PRISMO GULF ESTABLISHMENT', '025555939', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TALA CONCRETE REPAIRS & CONTRACTING LLC', '025502021', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ZAWALI KHAN DRINKING WATER', '0558380900', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CONTROL ELECTRICAL ACCESSORIES CO LLC', '025542082', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ZIAD MAHMOUD ABU AMER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MATUZ BLDG MAT TR', '065391455', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BHIMBER GENERAL TRANSPORT', '0501877212', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FIVE STAR GENERAL TRANSPORT', '0555123511', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DAMAN', '026149555', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL RASHIDI SAND & PEBBLE TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAZAYA CLEAN', '026650399', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMED AYUB AZAHAR STEEL TRADING', '02-5550255', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DAMASCUS KITCHENS', '03-721-2411', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL NASEER TRADING CO LLC', '037220701', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PILESTONE FOUNDATION & SURVEYING', '25558228', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'THREE STAR TECHNICAL WORKS LLC', '055-5886938', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NISR AL JAZEERA PLASTER TILES & PAINTS', '055-5293730', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MANZOOR CENTRAL A/C WORKS', '050-6916091', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALAF NAMAR PLASTER & BRICKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LULU CLEANING & PEST CONTROL SERVICES', '0505413780', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AMR MOSSAD MAHMOUD KARAM', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PERFECT MACHINERY & EQUIPMENT TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'STRONG ALLIED INT LTD', '04-368-7326', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DAO FENG TRADING -FZCO', '0559342782', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMAD RIYAD ISSA JABALI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FEDERAL TAX AUTHORITY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NOOR AL MAJED STATIONERY', '02-5510603', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAINBOW CITY CARPENTRY', '0557800568', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL QOWA AL SAREAA TECHNICAL WORKS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAFIQ KHAN KHEWA GUL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHABAB AL FAYOOM STEEL & PAINTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CASTLE GATES ALUMINIUM WORKS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SUPER SEVEN ELECTRICAL EQUIPMENT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HAPPY LINE AND MARBLE WORKS', '0504921050', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AZAD KHAN', '0507718192', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NAZAM ABBAS JUTT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SEA TOWER TRADING', '0505235997', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALUMINIUM WORKSHOP', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UMAR DIN MAJED KHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAFE LINE ELECTRICAL & MECHANICAL LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MODERN BUILDING MATERIALS TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MUZAFFAR KHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FINE EMIRATES HARDWARE TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GOLDEN SNOW ALUMINIUM & GLASS WORKSHOP', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SALEM ELDAWI MOHAMOUD ALI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SPINWAM WESTERN TRANSPORT & GENERAL CON', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHOBRA TECHNICAL SERVICES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHERTA GENERAL MAINTENANCE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHALALAT AL FAYOOM GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHIELDIN AHMED ZAKI ELMETWALLI ELSHAZL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABED HAJ ALALI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMED JAKIR ABU TAHER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAJA MANZAR IQBAL RAJA MUHAMMAD IQBAL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'WAHEED IQBAL SANITARY WORKS EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UTS CARRIER LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SAKHI TRANSPORT LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABU DHABI JUDICIAL COURT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SALEEM NHALIL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALI SHAN TRANSPORT LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TADEEM BUILDING EQUIPMENT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL DEYAR BUILDING MATERIALS  LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALFATEEN GENERAL TRANSPORT EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NATIONAL SURVEY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL EMAD TRADING CO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAJESTIC ENGINEERING CONSULTANTS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'REVIERA ENGINEERING CONSULTANCY LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NAJEM AL SAHRAA SCAFFOLDING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOSAIC BLG. MAT. TR. LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BOUSHRA EQUIPMENT LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MUHAMMAD MUSTAQ HEAVY EQUIPMENTS TRADIN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EMIRATES AUTOMATIC DOORS EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EMIRATES READY MIX', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DELTA TYPING & PHOTO COPY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CLASSIC BRIGHT GENERAL TRANSPORTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL AMIRAT MANUAL CARPENTRY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SINA FLOWER ELECTRICAL CO LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CH. IJAZ', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MARSTONE CEMENT PRODUCTS FACTORY LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL TELAL CEMENT TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ASHRAF AHMED MOHAMED KANDIL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'QINGDAO QINYUAN STEEL CO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MR.ADEEB HASAN MOHAMED ISMAIL ALHAMMADI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL KHASHB AL BANE CONCRETE CARPENTER CO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LULUAT AL BUSTAN BLDG MAT TR LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AMER AL HASSON REINFORCED CARPENTRY', '055 2033064', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL AWAZEL INTERNATIONAL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'IRAN BUILDING MATERIAL TRADING', '0501350825', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LINDEN GENERAL TRADING FZC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'COAST TRADING LLC', '072281471', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BAJWA TRANSPORT & HEAVY EQUIPMENT LLC', '0097172237612', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARCAL ENGINEERING CONSULTANT & INTERIOR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SADEEM BUILDING MAINTENANCE', '0505400888', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'REDEMEER STATIONERY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NASEEMUL JABEL GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HASTENWAY SHIPPING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CAOOKB BLOOTO DECORATION', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALFAN AL ZAABI TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ROVANA TRANSACTIONS FOLLOWING', '+97126210013', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHAREA AL GHARBIYAA GENERAL MAINTENANCE', '0551400645', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DESERT & SEA GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FARASHA BUILDING & RESIDENCE SERVICES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BAIT AL MONALIZA BUILDING MATERIAL TRAD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EMAD GAMAL TECHNICAL SERVICES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MOHEB CERAMIC & SANITARY WARE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HILTI EMIRATES LLC', '+97148854405', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL AIN AHLIA INSURANCE CO.(PSC)', '026119999', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAIF ALQUBAISI PUBLIC TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NAJAN ABBAS MUHAMAD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AMBULATORY HEALTHCARE SERVICES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMED ELSHAHAT IBRAHIM SHEHATA SHAABA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL QASR AL GHML CERAMIC & PLASTER WORK', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FIX WELL HARDWARE TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ADEEB HASAN MOHAMED ISMAIL ALHAMMADI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALID ZAMAN PLASTER & MARBLE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SELIEN GENERAL TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'IJAZ UL HAQ CHAUDRY ANSAR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AHMED HENO REINFORCED CARPENTRY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARC ELECTRICAL', '02-554-8270', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Q MIX READY MIX INDUSTRY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL FUTTAIM MOTORS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TRACK INTERNATIONAL FOUNDATION LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABU SAIFAIN CEMENT PRODUCTS EST.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MADAR EMIRATES FOR BUILDING MATERIALS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BAIT AL IBDAA SANITARY WARE & CERAMIC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TWAFEEG METAL INDUSTRIIES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ROKN AL KHOBRA BLDG. MATERIALS TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAHMOUD ANDULRAHMAN AL ZAHRY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MODERN HOME ENGINEERING CONSULTANCY LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'URUK ADVERTISING & PACKAGING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FAISAL NADEEM TILES & PLASTERING WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHUNTIAN DECORATION FZCO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALMUDESH MARBLE & GRANITE TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BUILDING COMPLEX GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ELNILE FALCON SANITARY WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FIRST CHOICE BLDG. MAT. TR.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RIYAD AHMED GEN. CONTRACTING CO LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HARP GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AHMED HASAN TRANSPORT LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHER NAWAZ DAUD KHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAIF MOHD AL SAYED PLASTER & TILES CON.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EXAA BUILDING MATERIALS TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ROCK CEMENT INDUSTRIES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL KALEEJ AL FEDII SCAFFOLDING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARAB CENTER FOR ENGINEERIING STUDIES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARAB MARBLE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAHMOUD ABDELLATIF ELSAYED IBRAHIM', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'JASSIM MOHAMED HASAN GEN MAINT.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SARB GEN. TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL ENAS GEN. MAINTENANCE EST.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL AANE AUTO ELECTRICAL & AIR CONDITIO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'WHITE PEACOCK FOR INSTALLATION & MAINT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AHMED GHONAIMY BUILDING CONT. LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EMIRATES BLOCK FACTORY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AAR CONCRETE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MONTASER KHALAF HAFEZ MAHMOUD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MASIYA SCAFFOLDS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HIGHTECH ELECTRIC & SANITARY CONTG', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LINK PAINTING WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL RAHMA STATIONERY TRAD. & ELECTRONIC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BAHAA RASHED NASSER ABDULLA ALMAZROUEI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAIDAN AL SAMHA GARDEN CONT & GEN TRANS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL KHASHAB BUILDING MATERIALS CO LLC.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALFUN ALASEEL BUILDING MAINTENANCE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PATEC STONES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'IMBA BUILDING MATERIALS TRADING LLC.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BARNALA HEAVY EQUIP. RENTAL & BLDG E', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DANUBE HOME LLC.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DANA STEEL PROCESSING INDUSTRY LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MASTER TIGER GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMED ELKHOLY ALUMINUM & GLASS WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UNIBETON  READY MIX', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARABIAN PALACE DECORATIONS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DOMUS CEMENT PRODUCTS INDUSTRIES LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'STAR WAY GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TAWASUL INSURANCE SERVICES LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'IBRAHIM MOHAMMAD IBRAHIM ALII AL QURSI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BAIT AL SHARQI SANITARY WARE & CERAM', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHINEX CARE GEN MAINT & CLEANING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MUGHNI TILE WORKS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RIGHT GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BAAYA CERAMIC & MARBLE WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALAF HASAN ABDULLAH AL HAMADI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MIZAN FIDHI BLDG MAT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MUAWIN IMPORTING & TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL TAJ AL MALEKI PAINTING & DECORATION', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL ARABIA FOR ELEVATORS & MOVING SYSTEM', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL ASRI SANITARY,TILES & MARBLES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL TAJ AL MASY PLASTER,TILES & PAINTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FAZAL SUBHAN HEAVY EQUIPMENTS RENTAL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ROYAL VOLTAGE ELECTRO MECHANICAL WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL WAQN SANDS PLASTERING WORKS EST.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ROSALIA MARBLE EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ZOOM BUILDING MATERIALS TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BAIDAQ TECHNICAL SERVICES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BIN MOOSA & DALY LTD LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'JUTT CHHAL GEN TRANSPORT EST.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ISMAIL KHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOUNTAIN HEIGHT ELECTRICAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAID REHMAN QATAL KHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALTOUFEER CONSTRUCATION & GEN.  MAINT.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PASCO PAVING STONES CO LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABNAA SOHAG BUILDING CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALFANMOHAMED RASHED ALMANSOORI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HEAVY MACHINARY RENTAL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SKYWAY TRADING CO. LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DREEM STAR CONTRACTING & GEN. TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TARGET STONE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL RAIDA ALUMINIUM WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'OSAMA MOHAMED EZZELDIN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BASHEER MARBLE & GRANITE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TERRAZZO LTD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'METALLIC EQUIPMENT CO.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EXPRESS METAL WORKS INDUS. LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MASHREQ DIESEL PUMPS REPAIRS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GUJARAT BUILDING CINTG. LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MATRIX LABORATORY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SETEX GENERAL TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'POWER STONE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMED ALI MOHAMED GEN TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'THREE FRIENDS GEN TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL HAMOOR ALUMININUM', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NAZO BLDG. MATERIALS TRDG. EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL KULAIB BUILDING MATERIALS TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HANY EDWARD SOBHY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ISTANBOUL ELECT. WARE TR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ELECTRA ABU DHABI LLC.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'OLD NAVY ELECTRO-MECHANICAL WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ISMAIL KHALEEL ISMAIL DARWISH ALHOSANI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ROYAL TOWER FOR MAT MKTG ENGINEERING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PARENTS PARADISE GEN TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HADAD SANITARY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAJAB TRADING CO LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALEEL AL BLOSHY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NEDAL MULHEM ALI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SALEM MOHSEN AL BARAIKI WELDING BLACKSM', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL JABEL ALSHAQ CENTRAL AC WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TECHNICAL SUPPLIES & SERVICES TRDG CO L', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALI JUMA STEEL & WELDING WORKSHOP', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MUHAMMAD NABI GHAZI KHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GEMINI TECHNICAL INDUSTRIES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BOOM TRADING CO LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FOUR STAR HARDWARE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHAMSER SINGH ISHER WELDING STEEL WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SWAID ALENMA SCAFFOLDS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL AMARA ALBRINZYAH MAINT. & PROPERTY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MASOOD  UR REHMAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAMA AL FURAT DECORATION LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ADVANCED PROCUREMENT FOR GEN. TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SAHWA GEN. TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SADARA GEN. TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHD. HASAN FARAJ POUR BLOCKS WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TOOT GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NATIONAL ENGINEERING BUREAU', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'VERROENGINEERING CONSULTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BENBONE ELECTRICAL CO LTD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BEST WAY HARDWARE TRADING EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL JALAL ELECTRICAL TRADING CO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAEED MARZOUQ AHMED ABDULLA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALIL HASSAN ABDULLA MUHSIN ALMEHSIN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALIFA IBRAHIM MOHAMED SALEEM', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAQSOOD AND SAGHEER GENERAL CONTARCTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL FAIHA ROSE REINFORCED BLACKSMITH', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HIGH HOME CERAMIC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CAIRO KICHEN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HIDAYATH TRADING CO LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SKILLED TECH INFORMATION TECHNILOGY SER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'WALID DAOUD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GHANTOOT INTERNATIONAL REAL ESTATE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAJAB GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BLUE RHINE  GENERAL TRADING ABU DHABI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL GURG FOSROC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AFZAL AHMED', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'READY MIX BETON', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NOORA DIN JAN GUL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AHMED CORE CUTTING SERVICES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NOOR ASADI GLASS AND ALUMINIUM FACTORY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'OMAR HUDAIB TRANSPORT AND GENERAL CONT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SUNDUS A/C WORKS AND SUPPLIES ESTABLISH', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RED ROSE CEMENT PRODUCT TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABIDOS STAR DECORE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL AMANA MARBLE & GRANITE FACTORY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAQEEB JINAB SUBHAT KHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RIGHT CORNER ALUMINIUM & GLASS EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MUKARRAM GENERAL MAINT.CONT.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SUKHOOR EMARAT MARBLE LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LIGHT MAGIC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALFAKHR PAINTING & DECORATION WORK', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARABIAN GERMAN CO. LTD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'OBEDIENT TECHNICAL WORKS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ELSAYED MOHAMED IBRAHIM ABDELATY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DAR AL KHAIR AGRI. EST.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMAD YOUNUS SHOHEL SHAJAHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MANAZEF TILE WORKS EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SMART HUB-ABUDHABI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MALEK AL MEHRI ALUMINIUM AND GLASS WORK', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAEED SULTAN ALSHAMSI TECHNICAL SERVICE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL HASEEB GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAFEER AHMAD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAIF UR REHMAN ABDUL REHMAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UMAR DRAZ MALIK MUHAMMAD NAWAZ', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHALSA OBEROI TRANSPORT EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BRIGHT HAND CONTRACTING AND GENERAL MAI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BELAL AZIZUL HOQUE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BIN FADEL AL MAZROUEI READY MIX EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SANITARY MATERIALS CO.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARABIAN INDUSTRIAL CO LCC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AQUAZONE LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ZAFAR IQBAL ELECTRICAL APPLIANCES REPAI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ACME ELECTRIC SWITCHGEAR LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL NAKHEEL TRADING EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CITY WINDOW DOOR & WINDOWS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BADAR CAPENTRY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NOOR AL SHAM ELECTRICAL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BAB AL QASR TECHNICAL SERVICE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAIDAN AL MAHABA GEN TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AGE STEEL LIMITED', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), '24 HOURS SERVICES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MIRZA & BAHRAM', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UNITED IRON AND STEEL COMPANY LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TECHNO TREND NETWORK SOLUTIONS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'WAHID HENDAWY ALUMINIUM AND GLASS CO LL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BEST CHINA MARBLE AND GRANITE IND.LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SULTAN INDUSTRIAL CEMENT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'VARIETY HARDWARE CO LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EMIRATES VISION METAL WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMAD DAWOOD ALMARZOUQY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FEDEX EXPRESS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'IRFAN MEHMOOD MUHAMMAD YAQOOB', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TRADITIONAL ORIENT ELECTROMECHANICAL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMED JASHIM UDIN BADIULALAM', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LATEEF KADHIM NASER NASER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HAPPY STAR CARPENTRY & ALUMINIUM WORKSH', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL ROWAY AL MOSTAQBILH TILING & MARBLE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL RAFEE ALUMINIUM AND GLASS DOOR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BAYNUNAH LABORATORIES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL HADIQAH GEN TR LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BEAUTY DESIGN METAL SHAPING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'OMAN INSURANCE COMPANY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DUBAI ISLAMIC INSURANCE AND REINSURANCE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PROFESSIONAL TILER TECHNICAL SERVICES L', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EXCELLENT PASSENGERS TRANSPORT BY RENTE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL OBAIDLI AND AL ZAROONI LEGAL CONSULT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HENKEL POLYBIT INDUSTRIES LTD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NEW LIGHT LIGHTING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SALHIYA LIGHTING CENTER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ANWAR AL REDHA GENERAL TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ATEF HUSSAIN MUHAMMAD HUSSSAIN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CORNER TILES AND MARBLE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL IBTISAM MARBLE & NATURAL STONE LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ROCHE ANTHONY PATRIC STANDEN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CUBE ART DECOR AND ADVERTISING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ILYAS BISMILLAH JAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RAJA AZHAR IQBAL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ELSEWEDY INDUSTRIES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ROOF CARE INTERNATIONAL MATERIALS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALRUWAD ALUMINIUM & CAPENTRY WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'OSAMA MOHAMED EZZELDIN ELHEGGAWY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FLOWER PALACE TILE WORK', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARABIAN PROFILE CO LTD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'QITAF HYDROPONIC AND ORGANIC FARMS PROD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'METHAQ TAKAFUL INSURANCE COMPANY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ZAKA ULLAH MUHAMMAD WARIS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ATIF HUSAIN MUHAMMAD HUSSAIN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MUNAWAR HUSSAIN CHOCHAN ATTA MOHAMMAD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HAFIZ ANWAR UL HAQ CHOHAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARGENTA CERAMIC MARBLE&SANITARY WARE TR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL KAWKAB AL AHMAR TECH.SERVICES LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FRAMECAD STEEL PRODUCT TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MR. NAJEEB ALHAMADI -SCP30', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PREMIUM CUT CARPENTRY WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'THRE E STARS CLEANING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ECOCON INDUSTRIAL LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAEED AL MERAIKHI REPAIRING AIR CONDITI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAEED AL ZAABI GENERAL TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FARAIDOONI TRADING CENTER', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL ANAAM ALUMINIIUM&GLASS FIXING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ISHRAZ GENERAL TRASNPORT AND CONTRACTIN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'APEX TRADING CO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PREFECT MACHINERY & EQUIPMENT TRADING &', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KARISMA KITCHENS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CARNEGIE CONTRACTING AND GENERAL MAIN.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MADA SAND TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMED ALI CHEHADE', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KUNOOZ ENGINEERING CONSULTANT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SIGN GOLD PASSENGERS AND TRASNPORTATION', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAJEED AL HOSANY -SCP37', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ZAHID TRANSPORT-IBRAR AHMED', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'NASEEM AL EBDAA DECORATION AND INTERIOR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LAROSA CONTRACTING AND GENERAL MAINTANA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALPHA ALMUTHAQADIMAH GENERAL CONTACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SAQAR ARABIA GENERAL TRASNPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL RAEY GENERAL TRASNPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOVING WHEELS GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MR.ADIL AL ZORAIQY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL RUWAIS ELECTRICAL & MECHANICAL EQUIP', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MANAA METAL CONSTRUCTION COMPANY LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AFREEN BUILDING MATERILAS TRADING CO LL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHD.MOHSEN MOHD.ALFAQEEH ALAMOODI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MULTI-AIR LECTRO MECHANICAL CON LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DAYAL BUILDING MATERIALS TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HARIWAR CONSTRUCTION & DEVELOPMENT LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'QUEEN HOUSE SANITR WARE TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AHMED.MOHSEN MOHD.ALFAQEEH ALAMOODI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAMA AL WATAN TECH. CONT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DRYWOOD CARPENTRY AND ALUMINIUM', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SPECIALIST UPVC WINDOWS AND DOORS FACTO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AWAD HANAFY AMIN ABDULREHMAN', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SAFEER ALKHAIR CLEANING SERVICES', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ADALAR GENERAL CONTRACTING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LATEST MACHANICAL EQUIPMENT LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABDELRAHMAN ATEF MOHAMED', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMED ELBOSATY MARBLES AND STONE WOR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL MINHAL-ABDULATIF ALCHAR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHERIDAN SPECIALIZED BUILDING PRODUCT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RASHED SAIF RASHED BUAFRA ALMEHRI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAJID MUSTHAQ MUHAMMAD MUSTHAQ', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FAMS TECHNOLOGIES LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMED AYYUB BLACKSMITH & WELDING W/S', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HAMAD ABDUL RAHMAN PLASTER TILES AND PA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BASSAM TANK TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SKY LINE ALUMINIUM AND GLASS WORKS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Aliaksandr Afanasyeu', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'EDENRED PREPAID CARD MANAGEMENT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARKAWEET ELECTRO-MCHANICAL LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TRITON GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMED ZAFAR STEEL WORKSHOP LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UAE ENTERPRISES COMPANY LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL WADI SANITARY WARES COMPANY LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SHANGHAI FENGYI SUPPLY CHAIN MGMT CO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AROUND THE WORLD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UNION REBAR FACTORY L.L.C.', '025500177', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ARD AL KINANA STONE & MARBLE WORK EST.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOUNTAIN WAY BUILDING MATERIALS EST', '025557437', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'LEVEL UP KITCHENS & METAL WORKS', '0555533524', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DESERT STAR STEEL TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DESERT DRY INSULATION', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BITCOIN COSTING MOLD RENTING', '0565661133', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Khaleel Ceramics Co.LTD', '065335691', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'House of Bollts & Fastening Accessories', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Ascon Equipment Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Shahamah Gat General Transporting', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'M.Zakria M.Ashraf', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Arabesque Laboratory for Soil Testing', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Furat Corner Carpentry & Reinforced', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Oriental Tower Maint Equip.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TAREQ ALI MOHD SADEQ AL BALOUSHI', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL Buraq Allamea Central A/C Work LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL Hadhoudh Trading & Cont.EST.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mohammad Ashfaq Nadir', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Abdulkarim Al Hommida', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Abu Raffat Shuttering', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SATKHIRA Electrical& Sanitary Shop', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Sad Al Jazeera Reinforced Carpentry', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BBM Building Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Abir Ceramic Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Nasir Mehmood Muhammad Aslam', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Fardoos Building Material Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Shanzalzeh General Contracting', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Specialised For Aluminium & Glass Works', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Waqas Al Chaudhry', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Aqua Bravo Water Desalination Eqpt.TRDG', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KASCO General Transport', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'RANA M.ITTIFAQ', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Red Zone General Transport Sole', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Wadi al sarooj Transport', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Golden Moon Hardware', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'New Al Khalidiya Aluminum & Glass Co.LL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Missouri Block Plaster Works', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Wurth Gulf LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHD ZABED STEEL TRADING COMPANY L.L.C', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL SANAA HARDWARE TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SEA WAVE ELECTRICAL TRADING', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALLIANCE MECHANICAL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'majid mushtaq muhammad  boom rent', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MUHAMMAD ZULFIQAR JAHANA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SEA ROAD GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MUSARAT NAWAZ & SHAHID ASLAM', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Khowahir Chemicals Mat.TR.LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BEST TRUCK GENERAL TRANSPORT', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Ahmed Core Cutting Service', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Dia Point Works', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Citron Transport', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mushtaq Ahmad Mian Muhammad', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GBMT Structural Steel', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Nice Villa General Maintenace', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Hussain Aluminium Co.W.L.L', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Tahir Ayub Dar', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Zinat Al Sahraa General Transport', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Casa Milano Building Materials Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Chaudhry Muhammad Ashfaqa', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Bagnodesign LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Jumaa Ahmed Alali', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Casa Bella Building Materials LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Fakhri Tools & Workshop Materials Tradi', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Advanced Concrete Technology', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Black Falcon Transport', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Sweet Voice Pest Control & Building', '024441533', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Star Glass & Aluminum Co', '065280335', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Hira Industries', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'United Arab Emirates Enterprises', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'FAHAM DOORS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TEE DEE Trading L.L.C', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Abu Mohammed', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Khaleej Equipment & Industrial', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al FATAH International Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Reda Industrial Materials LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Rukn Al Fares TR.Co.LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Master Builders Solutions Construction', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AAMIR SHAHZAD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Reef Al Junoobi Marble', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Water Shield Insulation Works', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Shams Fasteners & Accessories', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Cool Point Central AC& GeneralMaintena', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Gate Sialkot Gen.Transport', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Ecolit Building Contracting L.L.C', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Professional Team Electro&Mechanical', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Dalma Aluminium & Glass', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Ibrahim Ahmed Cement Board Fixing', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Alfan Al Meamary Stones', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Sayed Al Zujaj Tr LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Tsamim Wooden Aluminium Products', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Wadi Asas Al Fajr Stone Instl Works', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Mawared Kitchens', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Fakhama Doors', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al fan Al Meamary Stones Tr.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Joginder Singh-Ceramic Fixing', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Sultan Mahmoud General Maintenance', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Stable Electric LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Proformer Rollform Machinery Corp', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'High Class Doos&Window Factory', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Mohandes Metal Coating', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Outlet Ceramic LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Bin Fadel Almazrouei Ready Mix', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Das International Sole Propritorship', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Terraco UAE Ltd.Co.LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Hassan Abudief Kamel', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Caparol Paints L.L.C', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Monuyar Electrical', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mohamed Arsad', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Thahab Alsahraa Carpentary & Black Smit', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Chittagong BLDG.MAT.TRDG.CO L.L.C', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Gulf Perlite', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Anisha General Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'UK ROOF TILES LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Asia Al Noor Building Materials', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Lustre Lighting Solutions', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Forsan Al Sahra Aluminium and Glass Wor', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Altius Industries LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Rashid Paint', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Veik Building Materials FZCO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Ula Aluminum & Steel Work', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Dream House Building Materials', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Sohail Trailer', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Bin Nasser Hardware Trading Co.LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Abdul Rahman Al Zubedi Gen.TR.LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Afreen Building Materials Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Corys Build Centre LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mohamed Fatouh Abdelaziz', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mango A/C', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mazhar Shahzad', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Theqah Scaffolding', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Life Line TR CO LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Ibraheem Lahzy', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Yabrood Waterproofing', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Bait Al fakhama Techhnical', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Nature Home Building Materials', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Ahmed Marzouk Mostafa', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'QCON General Trading LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Aman Integrated Solution', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Junaid Talib', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Jory Kitchen Equipment', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mostafa Eid Aedelhalim', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Expect General Trading LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Husain Al Hashemi Gen.Cont.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Elyas-Pile Wrk', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Azem Scaffolding & Scrap', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Mushkat Elect.Switch Gear Control', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Shams Said Constuction', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Loaloat Al Batin Plaster Works', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mohamed Nashaat Ibrahim Plaster Works', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Exeed Premium Dry Mortar', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BD Profile Iron Work Est', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Golden ARC Metal Works LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Abu Aiman Shutter', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mohamed Moustafa', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Grand Foot General Maintenance', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Knooz Elnel General Maitenance', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Decorative Painting & Decor Works', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'National Cont. & Industrial Co.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Walid Ibrahim -Alumiunm WRK', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Mezin Building Material Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'WADI AL RAFIDAN CENTRAL AIR Conditiong', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Satari Trading LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'PASCO ALMADINA Building Materials Tradi', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'United Link', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Evergreen General Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Alu Tech Aluminium and Glass Work', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'WADI ZAMZAM CARPENRTY', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Unibeton Ready Mix', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'National Cont.Industrial', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'New Mix Ready Mix Industry', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'THE RED SQUARE EQUIPMENTS REPAIR', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Ilyas Ayub Dar Ajman-Rent', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Hussain Karim Back filling', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Solid Steel & Welding Works LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'International Tiles & Marbles', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SMKA Electric LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Magma Fasteners', '042965822', NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ATYAF DECORATION LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'JOINTECH FIRST AIR CONDITINER MAINTAINA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Deo Al Wosta-Amir mahmoud Taha', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KHATOT ELETHAA TRADING-SOLE PROPRIETORS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'HAITAM MOHANNAD AHMAD', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'DESERT EMPIRE BUILDING MATERIALS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'BLOCK MASTER INDUSTRIES Sole Proprietor', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AIN ALKHALEEJ PASCO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BASSEM PAINTS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'CLASIC LAND ALUMINIUM & GLASS WORK LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Windar Aluminium', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'F1 FOR ROAD CONTRACTING EST', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MOHAMMED SHAFIUL ALAM BUILDING MATERIAL', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TORINO ELEVATOR INSTALLATION & MAINTENA', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL AMEERASH PRINTING PRESS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ABC CERAMICS ABC BUILDMART LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'YOUNUS TRADING  EST.', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'SIMCO INDUSTRIAL MACHINES TRD.CO.L.L.C', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL WADI BUILDING MATERIALS', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'GREEN VALLEY INSTALATION OF SWIMMING PO', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MULBERRY ROSE CERAMIC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Kanz Chemical Ind.LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Modern Block Factory', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Sharp Aluminum and Glass Works', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Nassrawi Trading L.L.C', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Celia Buildings Material-LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Shazalzeh general Contracting And Shop', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Galal Mohammed Galala (Jalal)', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Najwa Aluminum Cont', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Right Way Umbrellas Installation', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Taqeef Middle East', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Nasmath Alkhayer AC Repair And Maintenc', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ALF LON Trading L.L.C', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Lighting Gallery LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Khalid Muhammad Sharif- Subcontra', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Italiano for Kichens & Closets', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'High Quality For Doors & Window', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mithaq Al Bina', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mozaik kitchens', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Classic Land Aluminium & Glass Wrk LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Rouba Al Badiya Gypsum Work Com LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Oryx Mix Concrete Manufacturing', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'ELITE POWER TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Qelaa for Marble Chips', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Spike Marbles', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'KREDENCE STEEL TRADING LLC SOC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Maha Marbles', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'TAXUITY ACCOUNTING SOLUTIONS LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Mazda Adel LLC', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Sufian-Excavation', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Aram Tejarat Jonoub', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Al Sabouh Building Material', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Muhammad Yasin Nawab', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Leca Building Material Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Amaco Concrete Industries', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Deep Tech for Contracting', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Iftikar Ahmed Tiles', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Meraj Ata Mohamed', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Micro Concrete Trading', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Moustafa Dahesh Sedki', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Transgulf Cement Products', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'Omar Saad-Shutter Work', NULL, NULL, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'AL BOOM TRADING LLC', NULL, NULL, 'ACTIVE', NOW(), NOW())
ON CONFLICT DO NOTHING;