-- Seed materials/products from Materials List (66 entries)
-- Run in Neon SQL Editor
-- Product schema: id, sku, name, unitOfMeasure, minStockLevel, currentStock, status, createdAt, updatedAt

INSERT INTO "Product" (id, sku, name, "unitOfMeasure", "minStockLevel", "currentStock", status, "createdAt", "updatedAt")
VALUES
  (gen_random_uuid(), 'MAT-001', 'Polythene Sheet', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-002', 'Shovel', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-003', 'Buckets', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-004', 'Wood nails', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-005', 'Steel nails', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-006', 'Line dori', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-007', 'Right Angle', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-008', 'Plum bob', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-009', 'Brushes', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-010', 'Waterproof bitumen drum', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-011', 'Garden hose pipe', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-012', 'White wood (Murabba)', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-013', 'Masking tape', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-014', 'Bending wire', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-015', 'GRP Water cabinet', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-016', 'PPR Gate valve', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-017', 'Brass Gate valve', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-018', 'Brass nipple', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-019', 'Brass tank connector', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-020', 'Asian W/C', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-021', 'P Trap', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-022', 'Bibcock (tap)', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-023', 'PPR Socket', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-024', 'PPR Pipe', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-025', 'PPR Union', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-026', 'PPR male socket', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-027', 'PPR Elbow', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-028', 'PVC Pipe', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-029', 'PVC Reducer bush', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-030', 'GRP Electric box with meter ADDC', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-031', '16mm 4C Cable', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-032', 'Earth Rod', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-033', 'Cable Glands', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-034', 'Cable lugs', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-035', 'Insulation tape', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-036', 'Concrete Manhole Cover', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-037', 'Fix Bolts', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-038', 'MS Hollow round pipe', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-039', 'MS Plate', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-040', 'Welding Rod', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-041', 'MS Hollow rectangular section', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-042', 'Plywood', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-043', 'Thinner', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-044', 'Enamel gloss paint orange', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-045', 'Temporary fence', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-046', 'Fence support', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-047', 'Fence clamp', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-048', 'Adjustable wrench', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-049', 'Thermal block 8" & 10"', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-050', 'Hollow block 8" & 4"', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-051', 'Solid block 8" (For drainage)', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-052', 'Solid block 4", 6" & 8"', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-053', 'Block mesh', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-054', 'Damproof for Blocks (Bitumen)', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-055', 'Black Cement', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-056', 'Block Angle (Hole pass)', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-057', 'Plaster cement', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-058', 'Rushcoat (Dashbond)', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-059', 'Rush machine/ Flicker machine', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-060', 'PVC Gurmala/ Sanding tool/ Plaster Trowel', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-061', 'Aluminium levelling bar/ patti', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-062', 'Plaster mesh', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-063', 'Angle bead', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-064', 'Fibre mesh', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-065', 'Joint tape', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW()),
  (gen_random_uuid(), 'MAT-066', 'Actfix - 345 (Concrete bonding agent)', 'Nos', 0, 0, 'ACTIVE', NOW(), NOW())
ON CONFLICT (sku) DO UPDATE SET name = EXCLUDED.name;