// UAE Emirates and their cities/areas

export const EMIRATES = [
  'ABU_DHABI',
  'DUBAI',
  'SHARJAH',
  'AJMAN',
  'UMM_AL_QUWAIN',
  'RAS_AL_KHAIMAH',
  'FUJAIRAH',
] as const;

export type Emirate = (typeof EMIRATES)[number];

export const EMIRATE_LABEL: Record<Emirate, string> = {
  ABU_DHABI:      'Abu Dhabi / أبوظبي',
  DUBAI:          'Dubai / دبي',
  SHARJAH:        'Sharjah / الشارقة',
  AJMAN:          'Ajman / عجمان',
  UMM_AL_QUWAIN:  'Umm Al Quwain / أم القيوين',
  RAS_AL_KHAIMAH: 'Ras Al Khaimah / رأس الخيمة',
  FUJAIRAH:       'Fujairah / الفجيرة',
};

export const EMIRATE_CITIES: Record<Emirate, string[]> = {
  ABU_DHABI: [
    'Abu Dhabi City',
    'Khalifa City',
    'Mohammed Bin Zayed City',
    'Shakhbout City',
    'Al Shamkha',
    'Al Rahba',
    'Al Wathba',
    'Al Falah',
    'Baniyas',
    'Al Reef',
    'Al Reem Island',
    'Saadiyat Island',
    'Yas Island',
    'Al Maqtaa',
    'Masdar City',
    'Al Mushrif',
    'Al Karamah',
    'Al Bateen',
    'Corniche',
    'Tourist Club Area',
    'Al Nahyan',
    'Al Rawdah',
    'Officers City',
    'Zayed Military City',
    'Al Riyadh',
    'Madinat Zayed',
    'Ghayathi',
    'Liwa',
    'Ruwais',
    'Sila',
    'Mirfa',
    'Delma Island',
    'Al Ain City',
    'Al Jimi',
    'Al Towayya',
    'Al Mutawaa',
    'Al Muwaiji',
    'Al Khabisi',
    'Al Maqam',
    'Al Sarooj',
    'Zakher',
    'Al Yahar',
    'Remah',
    'Sweihan',
    'Al Faqa',
    'Nahel',
    'Al Hayer',
    'Mezyad',
    'Al Ain Industrial Area',
    'Other',
  ],
  DUBAI: [
    'Deira',
    'Bur Dubai',
    'Downtown Dubai',
    'Dubai Marina',
    'Jumeirah',
    'Jumeirah Beach Residence (JBR)',
    'Palm Jumeirah',
    'Business Bay',
    'DIFC',
    'Dubai Creek',
    'Al Quoz',
    'Al Barsha',
    'Mirdif',
    'Al Qusais',
    'Al Nahda',
    'Al Rashidiya',
    'Al Warqa',
    'Al Khawaneej',
    'Al Mizhar',
    'Muhaisnah',
    'Al Twar',
    'Oud Metha',
    'Al Garhoud',
    'Festival City',
    'Dubai Silicon Oasis',
    'Dubai Investment Park (DIP)',
    'Jebel Ali',
    'Al Quoz Industrial Area',
    'Al Lisaili',
    'Dubai South (Expo City)',
    'Dubai Hills Estate',
    'Mohammed Bin Rashid City',
    'Nad Al Sheba',
    'Umm Suqeim',
    'Al Safa',
    'Al Wasl',
    'Satwa',
    'Karama',
    'Mankhool',
    'Meena Bazaar',
    'International City',
    'Discovery Gardens',
    'The Greens',
    'The Lakes',
    'Arabian Ranches',
    'Dubai Sports City',
    'Dubai Motor City',
    'Damac Hills',
    'Remraam',
    'Other',
  ],
  SHARJAH: [
    'Sharjah City',
    'Al Nahda (Sharjah)',
    'Al Khan',
    'Al Majaz',
    'Al Taawun',
    'Al Qasimia',
    'Al Yarmook',
    'Al Nud',
    'Bu Tina',
    'Al Mamzar (Sharjah Side)',
    'Muwailih',
    'University City',
    'Al Tai',
    'Hoshi',
    'Al Dhaid',
    'Kalba',
    'Khor Fakkan',
    'Dibba Al Hisn',
    'Other',
  ],
  AJMAN: [
    'Ajman City',
    'Al Nuaimiya',
    'Al Rashidiya (Ajman)',
    'Al Jurf',
    'Al Rawda',
    'Al Rumailah',
    'Emirates City',
    'Ajman Industrial Area',
    'Masfout',
    'Manama',
    'Other',
  ],
  UMM_AL_QUWAIN: [
    'Umm Al Quwain City',
    'Al Salamah',
    'Al Raas',
    'Al Dour',
    'Falaj Al Mualla',
    'Other',
  ],
  RAS_AL_KHAIMAH: [
    'Ras Al Khaimah City',
    'Al Nakheel',
    'Al Hamra',
    'Al Jazeera Al Hamra',
    'Al Mairid',
    'Al Rams',
    'Khuzam',
    'Dafan Al Nakheel',
    'Al Dhait',
    'Al Uraibi',
    'Julfar',
    'Digdaga',
    'Khor Khwair',
    'Al Ghail',
    'Wadi Shah',
    'Khatt',
    'Huwaylat',
    'Other',
  ],
  FUJAIRAH: [
    'Fujairah City',
    'Dibba Al Fujairah',
    'Khor Fakkan (Fujairah Side)',
    'Kalba (Fujairah Side)',
    'Al Faseel',
    'Al Aqah',
    'Mirbah',
    'Masafi',
    'Al Taween',
    'Qidfa',
    'Murbah',
    'Other',
  ],
};

// Legacy exports kept for backward compatibility with customers page
export const CITIES = ['ABU_DHABI', 'AL_DHAFRA', 'AL_AIN'] as const;
export type City = (typeof CITIES)[number];

export const CITY_AREAS: Record<City, string[]> = {
  ABU_DHABI: EMIRATE_CITIES.ABU_DHABI,
  AL_DHAFRA: [
    'Madinat Zayed', 'Ghayathi', 'Liwa', 'Ruwais', 'Sila', 'Mirfa', 'Delma Island', 'Other',
  ],
  AL_AIN: [
    'Al Jimi', 'Al Towayya', 'Al Mutawaa', 'Al Muwaiji', 'Al Khabisi',
    'Al Maqam', 'Al Sarooj', 'Zakher', 'Al Yahar', 'Remah', 'Sweihan',
    'Al Faqa', 'Nahel', 'Al Hayer', 'Mezyad', 'Al Ain Industrial Area', 'Other',
  ],
};

const snakeToCamel = (s: string) =>
  s.toLowerCase().replace(/_([a-z])/g, (_, c) => c.toUpperCase());

export const CITY_TRANSLATION_KEY: Record<City, string> = {
  ABU_DHABI: 'abuDhabi',
  AL_DHAFRA: 'alDhafra',
  AL_AIN:    'alAin',
};

export const areaTranslationKey = (area: string) => snakeToCamel(area);
